# Settings.yml
---
conf.py:
  project: TYPO3 Tutorial for Editors
  copyright: 2000-2015
  version: 6.2
  release: 6.2
  intersphinx_mapping:
    t3start:
    - https://docs.typo3.org/typo3cms/GettingStartedTutorial
    - null
    t3l10n:
    - https://docs.typo3.org/typo3cms/FrontendLocalizationGuide
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Tutorial-Editors
    github_branch: latest
  latex_documents:
  - - Index
    - t3editors.tex
    - TYPO3 Tutorial for Editors
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}

...
